apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: pangolin
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ= 
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: pangolin
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

